[theme]
# Рабочая палитра КлиматикА
primaryColor = "#1c5b75"
backgroundColor = "#f8fbfc"
secondaryBackgroundColor = "#eef5f7"
textColor = "#1f2937"

# Шрифт
font = "sans serif"

[server]
# Настройки сервера
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
# Настройки браузера
gatherUsageStats = false
